### ISSUE TITLE
Swipe to go back doesn't pop off stack

### ISSUE THREAD

**Issue by meno1** [LeoLeBras/react-router-navigation#1]
Great job on integrating react-router v4 into a feature navigation library.

If you go to the Huge example, click on Feed, click on an Item, click Next Item (3x), then swipe back 3x, you will see the back arrow in the Item header that can be pressed 3x to take you back (but this actually doesn't do anything since there is no where to go back).

Now repeat, but this time use the back button instead of swiping back.  You'll see that the back button disappears because it recognizes you have gone back all the way.

Also, if you hit the search tab, the search text is in the status bar.

**Comment by LeoLeBras** [comment]
Thanks for your feedback @addyosmani. I'll fix this issue in next release ([`dev`](https://github.com/LeoLeBras/react-router-navigation/tree/dev)).

**Comment by LeoLeBras** [comment]
New ```<Navigation />``` component now implements _swipe to go back_ !
