### ISSUE TITLE
Dynamically set header title

### ISSUE THREAD

**Issue by bjartebore** [LeoLeBras/react-router-navigation#17]
Is there a way of changing the header title of a card dynamically as with the setParam method in react-navigation?

I have tried with this without luck
`
<Navigation>
   <Card path="/path/:id" title={this.props.condition ? 'first' : 'second' } render={...} />
</Navigation>
`

**Comment by LeoLeBras** [comment]
Related to https://github.com/LeoLeBras/react-router-navigation/issues/10

**Comment by LeoLeBras** [comment]
This should be fixed in `1.0.0-rc.2`
