### ISSUE TITLE
BottomNavigation doesn't propagate location.state properly

### ISSUE THREAD

**Issue by CharlesMangwa** [LeoLeBras/react-router-navigation#19]
Let's say that I have 2 routes in my `<BotttomNavigation />` : `/home` & `/profile`. Inside` /home`, I have a `/home/article` route. 

I can pass props to `/home/article` thanks to `location.state`. But if I go to `/profile` from the `/home/article` and then go back to `/home/article` (by touching Home's icon in `<BotttomNavigation />`), I'll end up with a red error 😢 because,`/profile` didn't pass anything to `react-router` in `location.state`.

One of the solutions could be to re-inject the current state into `location.state` when the router is doing simple actions like `goForward()` or `goBack()` 🤔

Then, while navigating from `/home/article` to `/profile` the router will pass the current `location.state`, and if I come back to this route, the router is then doing a  simple `goBack()`, and I'll get my `location.state` back 😃. If I go somewhere else, the router won't pass this `location.state` to the new route because it won't necessarily need it!

**Comment by LeoLeBras** [comment]
Should be fixed in next release 😉 ([next branch](https://github.com/LeoLeBras/react-router-navigation/tree/next))
