### ISSUE TITLE
Dynamically adding Tabs

### ISSUE THREAD

**Issue by wilomgfx** [LeoLeBras/react-router-navigation#21]
Is it possible to add tabs (Tab component) dynamically for BottomNavigation and Tabs?

For tabs, when i push my new tab it shows only when i navigate back and forth to the screen which has tabs, but i want id like to see it appear right away. Same thing for BottomNavigation. 

Thanks :)!

**Comment by LeoLeBras** [comment]
I've never tried that, but it should be possible by just updating the routes array in the `<TabStack/>`component. I will implement this feature soon 😀.

**Comment by wilomgfx** [comment]
Great 👍  😄

**Comment by LeoLeBras** [comment]
Work in progress ➡️ https://github.com/LeoLeBras/react-router-navigation/issues/56

**Comment by LeoLeBras** [comment]
This should work in `1.0.0-rc.5`
