### ISSUE TITLE
When you call `history.replace` the title gets overlayed

### ISSUE THREAD

**Issue by niftylettuce** [LeoLeBras/react-router-navigation#22]
If you call `history.replace` and the current route has a title, and the new route has a title, then two titles will show in the navbar.

**Comment by niftylettuce** [comment]
<img width="312" alt="screen shot 2017-06-05 at 12 23 32 am" src="https://cloud.githubusercontent.com/assets/523141/26770474/3a3bfdc0-4985-11e7-8b98-5659de3c652c.png">

**Comment by LeoLeBras** [comment]
Related to #23

**Comment by LeoLeBras** [comment]
This should be fixed in `1.0.0-rc.2`
