### ISSUE TITLE
Error when pressing back button super fast

### ISSUE THREAD

**Issue by CharlesMangwa** [LeoLeBras/react-router-navigation#3]
<img width="330" alt="Screenshot of 'Huge' example" src="https://cloud.githubusercontent.com/assets/8975443/22953021/a0020964-f30f-11e6-9a6c-fdd62e4103e6.png">

Hi! This error appears in the `Huge` example when I go through `Next item` several times, and then press the back button super fast.

<img width="330" alt="Screenshot of console error" src="https://cloud.githubusercontent.com/assets/8975443/22952816/c1162bae-f30e-11e6-80da-430f2ce14a9a.png">

Hope it helps!

**Comment by LeoLeBras** [comment]
I also experienced this exact issue. I'll fix this issue in ```beta``` version.

**Comment by LeoLeBras** [comment]
Fix - https://github.com/LeoLeBras/react-router-navigation/commit/830e9329b62ea16729ed6305772759e8b59a8cc9
