### ISSUE TITLE
Strange behavior with Android back button

### ISSUE THREAD

**Issue by DiMoNTD** [LeoLeBras/react-router-navigation#37]
Hi.
I'm using `react-route` and `react-router-navigation` with redux.

I've setuped 2 links in `RootContainer` 

`RootContainer.js`
```
...
class RootContainer extends Component {

  _onPress () {
    window.console.log('button pressed outside of Navigation component');
  }

  render () {
    return (
      <View style={styles.applicationView}>
        <StatusBar hidden={true} />
        <Button title={"Button outside of Navigation"} onPress={this._onPress.bind(this)}/>
        <Navigation>
          <Card exact path={'/'} title="Menu" component={MainScreen}/>
          <Card path={'/barcode'} title="Barcode" component={BarcodeScreen}/>
        </Navigation>
      </View>
    );
  }
}
...
```

`MainScreen.js`
```
...
class MainScreen extends Component {

  static propTypes = {
    history: PropTypes.object
  };

  _onBarcodePress () {
    this.props.history.push('barcode');
  }

  render () {
    return (
      <View style={styles.container}>
        <Button title={"Barcode"} onPress={this._onBarcodePress.bind(this)}/>
      </View>
    );
  }
}
...
```

`BarcodeScreen.js`
```
...
class BarcodeScreen extends Component {
  render () {
    return (
      <ScrollView style={styles.container}>
        <KeyboardAvoidingView behavior='position'>
          <Text>BarcodeScreen</Text>
        </KeyboardAvoidingView>
      </ScrollView>
    );
  }
}
...
```

I've normaly walk through the screens, like:
`MainScreen` -> `BarcodeScreen`
then click BackButton on Android (not at NavBar), it back me to `MainScreen` (it's OK), than click BackButton on Android one more time, application exit to Android OS (it's OK too), then I run my application and.... `Button` component on `MainScreen` (inside of `Navigation` component) don't pressed (it's NOT OK), as if there is no click.
But interesting, that `Button` in `RootContainer` that outside of `Navigation` component can be pressed.

Why would this happens?

**Comment by DiMoNTD** [comment]
Here is a screenshot of normal rendered application in react devtools
https://prnt.sc/gho4tz

Here is a screenshot when I produce the behavior of the android back button
https://prnt.sc/gho60j

Take a look, that at last screen there is Null component

**Comment by LeoLeBras** [comment]
Hey @DiMoNTD ,
Can you create a GitHub repo to reproduce the issue you're having ? I will investigate this on next weekend. Thanks for reporting.

**Comment by DiMoNTD** [comment]
@LeoLeBras hi. To reproduce the issue, you can start your `Huge` example.
Here is the gif of the issue, I think it help you to understand what I mean.

![android back button problems](https://user-images.githubusercontent.com/1331473/30117334-995b5d04-9328-11e7-8c08-c19a4274ea1c.gif)

**Comment by LeoLeBras** [comment]
@DiMoNTD Ok thanks ! I'll take a look and come back to you shortly.

**Comment by DiMoNTD** [comment]
@LeoLeBras when do you plan to take up issues?

**Comment by LeoLeBras** [comment]
Hi @DiMoNTD I'm very busy at the moment with work and other stuff so my spare time is very limited. Next month, I will have free time and I might do all those things that you mentioned.
...  but PRs are welcome! 🔥

**Comment by DiMoNTD** [comment]
@LeoLeBras 
> ... but PRs are welcome! 🔥

OK, any idea, why this bug can be?
I thought, that problem in `history`, but with native `react-router` back button works fine.
What can block any action with React components after exit app with Android back button?

**Comment by DiMoNTD** [comment]
Found where is the problem.
Problem in `history.entries`. `PUSH` action add route to entries stack to `history.entries`. But `POP` action, don't pop the route from `history.entries` (because Back button and Forward button in browser make `POP` action, and all routes must be in `history.entries`). So when we push to entries Scene_1 > Scene_2 > Scene_3, and then click 3 time at Back button, `history.entries.lenght` is still 3. When Android applicaton exit with back button, history will saved, but component `CardStack` from `react-router-navigation` will be unmount. And when we start application, `CardStack` will build the navigationState with `history.entries` where we have 3 Scenes. So will render 3 `Containers`, and our actual `Container` with Scene_1 will be blocked by `Container` with Scene_3 (see the gif below). 

![rrn_back_button_bug](https://user-images.githubusercontent.com/1331473/31317400-2546ef7a-ac49-11e7-97fb-b4aa504fa3aa.gif)

To fix it, we need to get the last route, when application was closed, and reproduce actual route stack. I will do the PR

**Comment by DiMoNTD** [comment]
Here the PR
https://github.com/LeoLeBras/react-router-navigation/pull/43
