### ISSUE TITLE
Error when using Example from Readme

### ISSUE THREAD

**Issue by ma-pe** [LeoLeBras/react-router-navigation#42]
Hey,
first of all - thank you for maintaining this repo.

Using the first example of the Readme produced the following error:

`const App = () => (
  <NativeRouter>
    <Navigation>
      <Card
        exact
        path="/"
        render={() => <Link to="/hello"><Text>Press it</Text></Link>}
      />
      <Card
        path="/hello"
        render={() => <Text>Hello</Text>}
      />
    </Navigation>
  </NativeRouter>
)`

> React.Children.only expected to receive a single React element child.

Changing this line:

`render={() => <Link to="/hello">Press it</Link>}`

to this:

`render={() => <Link to="/hello"><Text>Press it</Text></Link>}`

resolves the error and renders the cards.

Greetings from Hamburg

**Comment by LeoLeBras** [comment]
Hey @ma-pe ,
Thanks for the feedback !
This error was normally fixed 2 months ago https://github.com/LeoLeBras/react-router-navigation/pull/31. Where can I find this example ?

**Comment by ma-pe** [comment]
Now I'm confused. I have been on the main Readme on the Repo-Overview. Now everything looks fine... Maybe I selected an earlier commit. Nevermind.

**Comment by LeoLeBras** [comment]
No problem !
