### ISSUE TITLE
undefined is not an object (evaluating e.route) the code is given below

### ISSUE THREAD

**Issue by gfairwanisynapse** [LeoLeBras/react-router-navigation#49]
import React,{Component} from 'react'

import {View,Text} from 'react-native'

import { BottomNavigation,Tab } from 'react-router-navigation'

export default class Main extends Component{

    render(){
        return(

            <BottomNavigation

            lazy={false}
            tabActiveTintColor="blue">

            <Tab label="Feed" path="/Feed" Component={require('./Feed')}/>
            <Tab label="Profile" path="/Profile" Component={require('./Profile')}/>

            </BottomNavigation>
        );
    }
}

**Comment by gfairwanisynapse** [comment]
Plz tell me the solution

**Comment by pyr0hu** [comment]
IMO There should be a Tab with a route of "/".
