### ISSUE TITLE
Tab blinks when mounted for the 1st time

### ISSUE THREAD

**Issue by CharlesMangwa** [LeoLeBras/react-router-navigation#5]
Hi!
As you can see on the image down there, the screen "blinks" when you mount a tab for the 1st time. I assume that this is cause by the fact that all tabs aren't mounted by default. 
I'm facing this in `_DEV_` mode so it probably won't occur in release mode, but just to point it out 🙂!

<image width="330" alt="GIF of blink bug" src="https://cloud.githubusercontent.com/assets/8975443/23106891/b6c51752-f6f4-11e6-89eb-30a924d069a4.gif">

**Comment by LeoLeBras** [comment]
Thanks for your feedback @CharlesMangwa.

```<BottomNavigation />``` will implement 2 new props for next release (beta) :
* **lazy** ```boolean``` : whether to load tabs lazily when you start switching
* **style** ```StyleSheet``` : override or extend the default style for ```<View />``` container

What do you think about this?

**Comment by CharlesMangwa** [comment]
Sounds like a nice idea! But would it mean that all the tabs could just be whether "lazily mounted" or not? In other words: would we have the possibility to choose which tab to load or not?

**Comment by LeoLeBras** [comment]
That's something very specific that could be resolved by writing a custom ```<BottomNavigation />``` for your own need :
```js
import React from 'react'
import { TabStack } from 'react-router-navigation'
import { TabViewAnimated } from 'react-native-tab-view'

class CustomBottomNavigation extends React.Component {
  renderScene = () => {
    // Load tabs lazily with your own needs
  }
  render() {
    return (
      <TabStack
        {...this.props}
        render={({ navigationState }) => (
          <TabViewAnimated
            navigationState={navigationState}
            configureTransition={() => null}
            renderScene={this.renderScene}
            renderFooter={/* Render a bottom tab bar */}
          />
        )}
      />
    )
  }
}

export default  CustomBottomNavigation
```

**Comment by CharlesMangwa** [comment]
Thx! That's exactly what I had in mind: looking forward to seeing the next update 👌

**Comment by LeoLeBras** [comment]
Fix - https://github.com/LeoLeBras/react-router-navigation/commit/dd9a6b853943bb1f701ada1942ae9de7ac56b1f7
