### ISSUE TITLE
Trigger route change from redux action

### ISSUE THREAD

**Issue by davidfloegel** [LeoLeBras/react-router-navigation#52]
Hi,

great navigation library!!

Just a quick question.. Is it possible to trigger navigation from an action creator in redux?
For example:
I want to log in a user, and after a successful login redirect the user to a specific page.

For now I'm listening to a `componentWillReceiveProps()` in my login component but that's very dirty...

Thanks!
David

**Comment by LaszloDev** [comment]
Hi @davidfloegel,

the routing in `react-router-navigation` is based on `react-router`. Wrap your Login component with `withRouter` to access the `history`-object and forward it to your redux action. On login success use `history.push('/new/route');` to redirect the user to another route.

LoginScreen.js:
```javascript
// ...
import { connect } from 'react-redux';
import { withRouter } from 'react-router-native';

class LoginScreen extends Component {
    // ..Component constructor & logic ...
}

const mapDispatchToProps = (dispatch) => {
  return {
    signinUser: (email, password, history) => dispatch(signinAction(email, password, history)),
  }
}

export default connect(mapStateToProps, mapDispatchToProps)(withRouter(LoginScreen));
```
signinAction.js
```javascript
const signin = (email, password, history) => {
  return dispatch => {
    dispatch(signinAction());

    signinService(email, password).then(
       // ....
       history.push('/login/success');
    ).catch(
       // ....
       history.push('/login/failed');
    )
  }
}
```
Documentation:
https://reacttraining.com/react-router/native/api/history
