### ISSUE TITLE
Share routes between BottomNavigation Tabs

### ISSUE THREAD

**Issue by davidfloegel** [LeoLeBras/react-router-navigation#53]
Hi,

I'm trying to share a view (for example a profile view) between different tabs.

At the moment my setup is:
```javascript
<BottomNavigation>
   <Tab />
   <Tab />
   <Tab />
</BottomNavigation>
```

Now I'd like to have my view `Profile` accessible from all those routes. Is that possible?

Cheers

**Comment by LaszloDev** [comment]
Hi @davidfloegel,

what you do mean by 'share a view'?

You can set Profile as a component of one `<Tab path="/profile" component={Profile} />` and then use the buttons of the `<BottomNavigation/>` or programmatically with the `history`-object of the underlaying `react-router-native` package to change the active route to it.

Checkout https://github.com/LeoLeBras/react-router-navigation/issues/52
