### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by alexisbronchart** [LeoLeBras/react-router-navigation#55]
Is any support for the iPhone X planned?
Right now the safe area layout guides don't seem to be used.

**Comment by nansthomas** [comment]
Please !! Add support for iPhone X !

**Comment by alexisbronchart** [comment]
Actually since this depends on react-navigation I guess we should use their SafeAreaView to achieve this...

**Comment by markv** [comment]
@LeoLeBras How far away is this feature? I'd like to keep using this package but this is holding me back.

**Comment by LeoLeBras** [comment]
@markv `react-router-navigation@1.0.0-rc.4` add partial support for iPhone X. The `minimal-app` example works on iPhone X but the other example `realm-world-app` is not. 

I didn't have time to investigate the issue. But as @alexisbronchart  suggested, using `<SafeAreaView />` should correct the problem.

Would you be available to help correct this issue and make the example work `realm-world-app`? 😍

**Comment by markv** [comment]
Using `react-router-navigation@1.0.0-rc.4` fixed the header overlap issue i was having

**Comment by LeoLeBras** [comment]
Work in progress ➡️ https://github.com/LeoLeBras/react-router-navigation/issues/56

**Comment by LeoLeBras** [comment]
@markv @alexisbronchart @nansthomas  iPhoneX support is live with `v1.0.0-rc.5` ! 📱
