### ISSUE TITLE
TypeScript type declarations

### ISSUE THREAD

**Issue by savovs** [LeoLeBras/react-router-navigation#58]
I'm super excited about this library. 😭 

Does anyone feel like working on TypeScript type declarations with me?
We can add them to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by LeoLeBras** [comment]
Hey @savovs ,
This PR adds typescript definitions to `react-router-navigation` (@kaoDev). I do not use TypeScript myself. I think the best thing to do would be to put this PR to https://github.com/DefinitelyTyped/DefinitelyTyped ! 😎

**Comment by LeoLeBras** [comment]
Oups, sorry I forgot the link of the PR : https://github.com/LeoLeBras/react-router-navigation/pull/36

**Comment by kaoDev** [comment]
hey sorry for the late response, I was a little occupied the last weeks.

@savovs I will transfer the PR today to DefinitelyTyped, but I will need some extra time to update it to the last changes since I opened it.

**Comment by LeoLeBras** [comment]
Awesome 😬 thank you very much !

**Comment by kaoDev** [comment]
the declarations got merged to the DefinitelyTyped Repo 😀  https://www.npmjs.com/package/@types/react-router-navigation
 
it took a bit longer than expected because I had a discussion about using types instead of interfaces
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23114#issuecomment-360244981

**Comment by NinjaSudo** [comment]
@kaoDev @LeoLeBras I'm setting up my project, how would I make sure that react-router-navigation has the TypeScript definitions?

would `yarn add react-router react-router-native react-router-navigation` simply work for my existing TypeScript project? or would I need to add some identifier to the TypeScript specifics?

**Comment by NeverFearTheasHere** [comment]
@NinjaSudo you would need to add the type declarations from DefinitelyTyped by running:
`yarn add @types/react-router-navigation --dev`
