### ISSUE TITLE
Tab Switch Unmounts Navigator Stack

### ISSUE THREAD

**Issue by zachrnolan** [LeoLeBras/react-router-navigation#61]
Two tabs using BottomNavigation:

```
<BottomNavigation
  lazy={true}
  tabActiveTintColor="blue">
  <Tab label="Accounts" path="/accounts" component={Accounts} />
  <Tab label="Profile" path="/profile" component={Profile} />
</BottomNavigation>
```

In the Accounts component, I have:

```export default class Accounts extends Component {
  componentDidMount() {
    console.log('Accounts mounted')
  }
  componentWillUnmount() {
    console.log('Accounts unmounted')
  }
  render() {
    return (
      <Navigation
        navBarStyle={{ backgroundColor: 'purple' }}
        titleStyle={{ color: 'white' }}>
        <Card
          exact path='/accounts'
          title='Accounts'
          render={() => (
            <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
              <Text>Accounts</Text>
              <Link to='/test'><Text>Go To Test</Text></Link>
            </View>
          )}
        />
        <Card
          exact path='/test'
          title='Test'
          component={Test}
        />
      </Navigation>
    )
  }
}
```

1. Tap on "Go To Test" Link
1. Go to other tab (Profile)
1. Come back to Accounts tab
1. Test Component is unmounted and the back button is still in the header.

Expected Result: Test Component shouldn't be unmounted when switching back to the Accounts tab. 

Is my setup incorrect?

**Comment by zachrnolan** [comment]
![ezgif-3-91f4d8984f](https://user-images.githubusercontent.com/66614/35001445-9f1c1faa-fa9b-11e7-86e8-9a14e721775a.gif)

**Comment by LeoLeBras** [comment]
Can you give me the version of `react-router-navigation` that you use?

**Comment by zachrnolan** [comment]
@LeoLeBras Thanks for the reply, I'm using `"react-router-navigation": "^1.0.0-rc.3"`

**Comment by LeoLeBras** [comment]
OK ! I can't reproduce your issue. Can you provide a reduced test case (repo) that highlights the problem?

**Comment by zachrnolan** [comment]
@LeoLeBras sent you an invite to my example private repo. Thanks for taking a look.

**Comment by LeoLeBras** [comment]
Okay, I just figured out the problem. When you swith to `/test`, the tab `/accounts` is no longer active.
You must therefore do the following:
```js
 return (
  <Navigation
    navBarStyle={{ backgroundColor: 'purple' }}
    titleStyle={{ color: 'white' }}>
    <Card
      exact path='/accounts'
      title='Accounts'
      render={() => (
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
          <Text>Accounts</Text>
          <Link to='/accounts/test'><Text>Go To Test</Text></Link>
        </View>
      )}
    />
    <Card
      path='/accounts/test'
      title='Test'
      component={Test}
    />
  </Navigation>
)
```
Hoping it might help you ! 😊

**Comment by zachrnolan** [comment]
@LeoLeBras Thanks, works as expected now. Appreciate the quick and helpful responses!

**Comment by zachrnolan** [comment]
@LeoLeBras Thinking back on this, why is it necessary to have test prefaced with /accounts? Say I have two tabs where each tab has its own navigator component. I have a shared screen called discover-people that I want to be able to link to from each tab. Do I need to have a card in each navigator that uses different paths?

Example:
/home
/discover

Each screen has a link to `discover-people`, it seems like I have to have two separate cards with paths `/home/discover-people` and `/discover/discover-people`.
