### ISSUE TITLE
TypeError: Cannot read property 'index' of undefined

### ISSUE THREAD

**Issue by mierz00** [LeoLeBras/react-router-navigation#66]
### Error: 
TypeError: Cannot read property 'index' of undefined when changing route with `<BottomNavigation />`

<img src="https://image.ibb.co/gaiasn/Simulator_Screen_Shot_i_Phone_6_2018_03_03_at_11_55_42.png" width='250' />

This navigation currently works.
`/ ` -> `/auth`  ->` /auth/contacts/`  -> `/auth/contacts/profile ` -> ` /auth/contacts/` -> `/auth/history`

However, if I try this navigation I will get the error.
`/ ` -> `/auth`  ->` /auth/contacts/`  -> `/auth/contacts/profile ` -> ` /auth/history`

The issue arrises from being in the nested `/auth/contacts/profile` route and then changing to another tab route. I am also using Redux to move to /auth/contacts/profile screen.

### My current setup is as follows:
AppScreen.js
```
<Navigation >
  <Card exact path="/" component={LaunchScreen} />
  <Card path="/login" component={LoginScreen} />
  <Card path="/auth" component={Viewport} />
  <Card path="/call" component={CallScreen} />
</Navigation>
```
Viewport.js ( Simplified code )
```
<BottomNavigation >
  <Tab path="/auth/contacts"  component={ContactsScreen}  />
  <Tab path="/auth/keypad" component={DialerScreen}  />
  <Tab path="/auth/history" component={HistoryScreen}  />
  <Tab path="/auth/settings" component={SettingsScreen} />
 </BottomNavigation>
```
ContactsScreen.js
```
<Navigation />
  <Card 
      path="/auth/contacts/profile"
      component={ContactProfileScreen}
   />
  <Card 
      path={'/'} 
      component={ContactsViewport} 
  />
</Navigation>
```

**Comment by jwill93** [comment]
Seeing the same outside of redux with the following setup:

Routes.js:
```
<NativeRouter>
    <BottomNavigation>
      <Tab exact label="Home" path="/" component={Splash} />
      <Tab exact label="Items" path="/items" component={ItemStack} />
      <Tab exact label="Settings" path="/settings" component={Settings} />
    </BottomNavigation>
  </NativeRouter>
```

ItemStack.js:
```
<Navigation>
    <Card exact path="/items" component={ItemList} title="Items" />
    <Card
      path="/items/:id"
      component={ItemDetails}
      renderTitle={({ match }) => (
        <Text>Item { match && match.params.id}</Text>
      )}
    />
  </Navigation>
```

Error can be provoked by:
Items tab press -> `/items/:id` Link press -> Home tab press -> Items tab press

**Comment by jwill93** [comment]
Investigated this on `v1.0.0-rc.4`

It seems like the code causing the error is the bit meant to fix #23 

https://github.com/LeoLeBras/react-router-navigation/blob/v1.0.0-rc.4/packages/react-router-navigation/src/DefaultRenderer.js#L128
```
const scenes = transitionProps.scenes.reduce((acc, scene) => {
      if (acc.find(({ index }) => scene.index === index)) {
        const indexOf = acc.findIndex(({ index }) => scene.index === index);

        return [...acc.slice(0, indexOf), scene];
      }

      return [...acc, scene];
    }, []);
```
The above function doesn't factor in the staleness of routes and ends up filtering out the only active route because it shares an index with a stale route. This ends up creating a scenes array which doesn't contain any active scenes which chokes down the line in react-navigator (https://github.com/react-navigation/react-navigation/blob/master/src/utils/getSceneIndicesForInterpolationInputRange.js#L9)

However, the stale scene is actually the scene you would expect to render (the item detail page in my case).

**Comment by LeoLeBras** [comment]
Hello @jwill93 @mierz00 !

`1.0.0-rc.5` will be released very soon et should fix your issue with a new [`<DefaultNavigationRenderer/>`](https://github.com/LeoLeBras/react-router-navigation/blob/master/packages/react-router-navigation/src/DefaultNavigationRenderer.js) core component.

Sorry for the delay in response

**Comment by LeoLeBras** [comment]
This should be fixed in `1.0.0-rc.5`

**Comment by jwill93** [comment]
The error mentioned above is resolved, but it still doesn't maintain your stack properly if you navigate to a different tab and then back. Happy to open a new issue for that with specific details and repro steps (same as those above) if helpful

**Comment by zachrnolan** [comment]
Also experiencing this issue. @LeoLeBras do you have any ideas on a path forward? I know `1.0.0-rc.5` isn't recommended at the moment.

**Comment by simonbuerger** [comment]
FWIW I worked around this by making sure all my tabs were not `exact` route matches (this does mean no "root" match either, so you'll need to handle getting to the first tab route with a redirect).

**Comment by zachrnolan** [comment]
@simonbuerger Thanks for the tip. I'm not using exact on my routes, but I did fix the issue just now.

I had `/home` => `/discover`, when it should have been `/home` => `/home/discover`. Now when I switch to another tab and back to home, it works as expected.
