### ISSUE TITLE
CardStyle doesn't work at all

### ISSUE THREAD

**Issue by skyskysky11** [LeoLeBras/react-router-navigation#67]
CardStyle prop doesn't work. How can I solve this problem? Grey background everywhere.

* Device: `Redmi 4A`
* OS: `Android 7.0`
* React-Native (version): `0.52.2`
* React-Router (version): `4.2.0`
* React-Router-Navigation (version): `1.0.0-beta.27`

**Comment by LeoLeBras** [comment]
This should be fixed in `1.0.0-rc.5`
