### ISSUE TITLE
Question: Possible to prevent swiping gesture

### ISSUE THREAD

**Issue by ma-pe** [LeoLeBras/react-router-navigation#69]
I am currently happily using `Navigation` to navigate through my App. 👍 

I have a process where the user may not enter earlier steps. I am hiding the back-button, but the user can still use the "swipe-right"-gesture to return to earlier screens.

Is it possible to prevent the user from using the swiping gesture (on single `Card`'s or the whole `Navigation`)?

I haven't found anything in the docs.

**Comment by LeoLeBras** [comment]
You can use new `gesturesEnabled` option - https://github.com/LeoLeBras/react-router-navigation/commit/80b7a0fd3a7e6a9a27b17a7e2e43132966588e10 😊

**Comment by ma-pe** [comment]
Love it!
