### ISSUE TITLE
BottomNavigation bugs with icons

### ISSUE THREAD

**Issue by CharlesMangwa** [LeoLeBras/react-router-navigation#7]
The router has some difficulties to render <BottomNavigation /> icons when we don't set icons for all tabs 🙈…

![rrn](https://cloud.githubusercontent.com/assets/8975443/23968386/cc9cff00-09c2-11e7-88c3-3c95a8beba9f.gif)

[EDIT]

It sounds ok when all the items are icons (not just labels).

**Comment by LeoLeBras** [comment]
Fix https://github.com/LeoLeBras/react-router-navigation/commit/778defedc64196a181a460f78fdb8cc783e01b47
