### ISSUE TITLE
Web support? Does it work with react native wb

### ISSUE THREAD

**Issue by txs** [LeoLeBras/react-router-navigation#74]
**Do you want to request a _feature_ or report a _bug_?**
...

**What is the current behavior?**
_If the current behavior is a bug, please provide necessary steps for reproduction of this issue, or better the reduced test case (without any external dependencies, if possible)._

1. ...

2. ...

**What is the expected behavior?**
...

**Environment (include versions). Did this work in previous versions?**

* Device: `...`
* OS: `...`
* React-Native (version): `x.x.x`
* React-Router (version): `x.x.x`
* React-Router-Navigation (version): `x.x.x`

**Comment by LeoLeBras** [comment]
I never tried to do that! But these two librairies : `react-native-tab-view` and `react-navigiation` work with this `react-navigation` so it should be the same with `react-router-navigation` !

**Comment by txs** [comment]
I tried it But seems like the history is different between react native web and react native. Hopefully you may  help out. I don't understand why to use import type "RouterHistory"  from react-router.... I go check react router couldn't find anything about RouterHistory.
Here is the error code: No history entries found
    at new CardStack (webpack-internal:///./node_modules/react-router-navigation-core/src/CardStack.js:1)
    at constructClassInstance (react-dom.development.js?3809:2050)

**Comment by ahmedu007** [comment]
We are using this with [react-native-web](https://github.com/necolas/react-native-web) on our current project, and it works. There is a branch on that repo, you would need to merge it and navigation is all setup for you

**Comment by mayankgenie** [comment]
I wanted to use BottomNavigation with react-native-web with static routing using react-router-config for ssr. Do you think it will work?

**Comment by mayankgenie** [comment]
@ahmedu007 do you have the link for the repo I can refer?

**Comment by LeoLeBras** [comment]
@txs @ahmedu007 @mayankgenie 
Hey ! I just released a new alpha version of the library. The [core of the library](https://github.com/LeoLeBras/react-router-navigation/tree/master/packages/react-router-navigation-core) no longer depends on react-native. 💪I created an example with [Shopify's Polaris](https://polaris.shopify.com/) web library to [show how it works](https://github.com/LeoLeBras/react-router-navigation/tree/master/packages/react-router-polaris). ([the example](https://github.com/LeoLeBras/react-router-navigation/tree/master/examples/polaris-web-app) of use and [➡️ the link](http://focused-blackwell-61841d.netlify.com/))
If some are still waiting for integration with `react-native-web`, I would be very happy to see someone create a PR about it.

**Comment by ahmedu007** [comment]
The quickest way to get started with React Native Web is to create a folder called `routing` (or something similar) and then create two files in there. `Routing.web.js` and `Routing.native.js`

Then you can use the following code:
`Routing.web.js`:

`export {
  BrowserRouter as Router,
  Link,
  Switch,
  Route,
  Redirect,
} from 'react-router-dom';`

`Routing.native.js`

`export { NativeRouter as Router, Link, Redirect } from 'react-router-native';

export { Navigation as Switch, Card as Route } from 'react-router-navigation';
`

And then in your `App.js`

`import { Router, Switch, Route } from './routing/Routing';`

**Comment by ahmedu007** [comment]
I found the starter kit with this lib. I'm sorry I mentioned it was on the same repo, but it was a different repo. Here is the link to it. Let me know if this needs to be in the docs, and I'll do a pull request for it.

https://github.com/joefazz/react-native-web-starter/tree/navigation-react-router

**Comment by LeoLeBras** [comment]
Hey @ahmedu007 , it would be great to have documentation on that. A PR is welcome!

**Comment by ahmedu007** [comment]
I'll try and get it done on the weekend!
