### ISSUE TITLE
Customise BottomNavigationBar?

### ISSUE THREAD

**Issue by CharlesMangwa** [LeoLeBras/react-router-navigation#8]
Is there any way to customise [BottomNavigationBar](https://github.com/LeoLeBras/react-router-navigation/blob/master/modules/BottomNavigationBar.js#L68)'s style properties?
It would be nice to be able to change it, the same way we do with icons and labels, without creating a whole new component. A little `style` prop should do the job 👌

**Comment by LeoLeBras** [comment]
Fix https://github.com/LeoLeBras/react-router-navigation/commit/778defedc64196a181a460f78fdb8cc783e01b47
