### ISSUE TITLE
Error when using NavBar within renderNavBar

### ISSUE THREAD

**Issue by nicollecastrog** [LeoLeBras/react-router-navigation#81]
**Do you want to request a _feature_ or report a _bug_?**

A bug, I believe

**What is the current behavior?**

1. I was having a play with the idea of a custom navbar, following the idea presented in the [guide blog](https://medium.com/the-react-native-log/thousand-ways-to-navigate-in-react-native-f7a1e311a0e8) ("React Router Navigation" section, point 3), and I'm unable to use `NavBar` at all

2. Code looks like this:

```js
<Navigation
  backButtonTitle="Back"
  renderNavBar={() => (
    <View>
      <NavBar {...this.props} />
    </View>
  )}
>
...cards here...
</Navigation>
```

3. Error is: `undefined is not an object`

<img width="340" src="https://user-images.githubusercontent.com/5670279/43462179-4ffcc790-94cd-11e8-92d0-dd061857a302.png" />

**What is the expected behavior?**

Expect to be able to render `NavBar` from within `renderNavBar` callback, as described in blog post and [docs](https://github.com/LeoLeBras/react-router-navigation/blob/master/docs/NAVIGATION.md#navbar-props). The idea is of course to the leverage existing `NavBar` provided by `react-router-navigation` and also add additional components to sit side-by-side with `NavBar` in the header

**Environment (include versions). Did this work in previous versions?**

I'm assuming it did work in previous versions, but as I only starting experimenting with the package today, I'm not sure.

* Device: `iOS Simulator - iPhone 6`
* OS: `iOS 11.4`
* React-Native (version): `0.55.4`
* React-Router (version): `4.3.1`
* React-Router-Navigation (version): `1.0.0-rc.4`

Thank you for any guidance you might be able to provide, loving this package so far 👍 😄

**Comment by LeoLeBras** [comment]
Maybe doing the following should fix the problem?
```js
<Navigation
  backButtonTitle="Back"
  renderNavBar={(navBarProps) => (
    <View>
      <NavBar {...navBarProps} />
    </View>
  )}
>
...cards here...
</Navigation>
```

**Comment by LeoLeBras** [comment]
Close due to inactivity
